ROM php:7.2-fpm-alpine

RUN apk add --no-cache pcre-dev $PHPIZE_DEPS \
        && pecl install redis \
        && docker-php-ext-enable redis.so

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer
